[WIP] Introduce pre-commit hooks
EducationalTestingService/skll pull request #650
Opened 2020-12-21 20:26 UTC by mulhod

I have not yet updated documentation on how to make use of pre-commit hooks. At this point, the hooks are installed as a development dependency, so this shouldn't affect anything in terms of packaging.

I have left out `black` for now because I don't want this getting too big and controversial. I will do that next separately so that we can all see what exactly will happen.

2020-12-21 21:53 UTC, pep8speaks commented
Hello @mulhod! Thanks for updating this PR. 















* In the file [`skll/data/readers.py`](https://github.com/EducationalTestingService/skll/blob/e5d7f724a4870d59528661626dcce1e0f79586df/skll/data/readers.py):

> [Line 50:1](https://github.com/EducationalTestingService/skll/blob/e5d7f724a4870d59528661626dcce1e0f79586df/skll/data/readers.py#L50): [F401](https://duckduckgo.com/?q=pep8%20F401) 'itertools.islice' imported but unused

2020-12-22 03:24 UTC, mulhod commented
Addresses #646

2021-01-04 21:09 UTC, desilinguist reviewed
Should we exclude the CSV/TSV/JSON files from the test data from the auto-formatting fixes?

2021-01-04 21:18 UTC, desilinguist requested changes
Everything else looks good to me! This will be quite useful! Just that one minor suggestion.

2021-01-04 21:53 UTC, mulhod commented
> Should we exclude the CSV/TSV/JSON files from the test data from the auto-formatting fixes?

I have gone ahead and excluded these files from the EOF file hook.

2021-01-04 22:29 UTC, desilinguist approved these changes
LGTM!

2021-01-05 18:26 UTC, bndgyawali approved these changes
I have a comment, but seems like that is how black does. 
Else everything looks good to me.

2021-01-05 18:26 UTC, bndgyawali commented on skll/learner/__init__.py
> +    RandomForestRegressor,
do we need a comma at the end?

2021-01-05 18:26 UTC, bndgyawali commented on skll/learner/__init__.py
> +    TheilSenRegressor,
here too.

2021-01-05 18:26 UTC, bndgyawali commented on skll/learner/__init__.py
> +    write_predictions,
and here

2021-01-05 18:26 UTC, bndgyawali commented on skll/learner/utils.py
> +    precision_recall_fscore_support,
seems it is having comma everywhere in this type of import statements.

2021-01-05 19:17 UTC, aoifecahill approved these changes

2021-01-05 19:18 UTC, merged