Replace MANIFEST.in with `package_data` in setup.py
EducationalTestingService/skll pull request #679
Opened 2021-03-10 16:04 UTC by RobertImbrie

This PR closes #674.
- Add package_data, exclude_data, and include_package_data methods to setup.py
- Delete MANIFEST.in

**Note:** Tested by running `python setup.py sdist build` once for each setup and running a diff on the generated folders. They were identical!

2021-03-10 16:13 UTC, RobertImbrie commented
Thank you, Nitin! I'm hoping to keep them going. :)

Also, glad to hear it went through easily this time!

2021-03-11 18:02 UTC, desilinguist commented
So, I have been playing around with this and I don't think these changes are giving us the desired result. Here are the things I tried:

1. If I remove `MANIFEST.in` and run `python setup.py sdist build`, `tests` and `examples` are correctly excluded but `LICENSE.TXT` and `requirements.txt` are *not* included. 

2. If I modify the `find_packages()` call in `setup.py` to not mention `exclude=['tests', 'examples']`  and run `python setup.py sdist build`,  `tests` and `examples` are _not_ excluded this time around and LICENSE.txt and requirements.txt are still _not_ included. 

3. If I modify `setup.py` to now add back `exclude=['tests', 'examples']` and then also add the following two lines to it, `tests` and `example` are now back to being correctly excluded but `LICENSE.txt` and `requirements.txt` are _still_ not included:
    ```python
    package_data={'': ['*.rst', 'LICENSE.txt', 'requirements.txt']},
    include_package_data=True,
    ```

So, I referred to the [relevant documentation](https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html?highlight=package_data) for `setuptools` and found this parenthetical nugget:

> Note: although the package_data argument was previously only available in setuptools, it was also added to the Python distutils package as of Python 2.4; there is some documentation for the feature available on the python.org website. If using the setuptools-specific include_package_data argument, files specified by package_data will not be automatically added to the manifest unless they are listed in the MANIFEST.in file.

So, what I tested next was to keep `MANIFEST.in` but to edit it to only keep the following lines: 
```
include LICENSE.txt
include requirements.txt
```

And this yielded exactly the same results as what we have right now (`README.rst` is already included so we don't need `include *.rst` either)

@RobertImbrie can you please edit this PR to make the following changes:
- Add back `MANIFEST.in` with the same two files.
- Revert any changes to `setup.py`.

2021-03-11 18:34 UTC, desilinguist requested changes
See my comment for suggested changes.

2021-03-16 19:53 UTC, RobertImbrie commented
Hi Nitin! I made the requested changes to the pull request.

Also, my sincere apologies for the issues! I had deleted the `build` directory but _not_ `skll.egg-info`, which should account for why my output was different. Next time, I will read the documentation more closely.

2021-03-16 22:17 UTC, desilinguist commented
Looks great! Thanks @RobertImbrie!

2021-03-16 22:17 UTC, desilinguist approved these changes

2021-03-16 22:18 UTC, merged