Rewrite docstrings for skll/data/readers.py
EducationalTestingService/skll pull request #686
Opened 2021-04-01 16:32 UTC by RobertImbrie

- Add space between parameters.
- Change ` to `` when referring to code.
- Remove 'optional' from parameters with default values.
- Move default values next to parameter names.
- Specify shape of arrays and array-likes.
- Update `skll.FeatureSet` and `skll.Reader` to `skll.data.FeatureSet` and `skll.data.Reader`
- Line up variables and text in `replace_blanks_with` parameter descriptions to improve legibility.

**Notes:**
Before the pull request is approved, I'd like to note that both instances of the `replace_blanks_with` parameter include a 'value' option with unspecified type, shown here:
```
replace_blanks_with : value, ``dict``, or ``None``, default=None
```

Later, in the parameter description, it says that this value must be numeric:
```
value   = A (numeric) value with which to replace blank values.
```

If that's the case, shouldn't we refer to it as `Number` instead of 'value'?

2021-04-01 22:57 UTC, desilinguist requested changes
Thanks @RobertImbrie ! Found a typo and also seeing some other issues that it's hard to show suggestions for. Will push a commit.

2021-04-01 22:57 UTC, desilinguist commented on skll/data/readers.py
> +        the data set is read into a ``pd.DataFram`e`.
```suggestion
        the data set is read into a ``pd.DataFrame``.
```

2021-04-01 23:18 UTC, desilinguist commented
@RobertImbrie please take a look at my pushed changes and see if they make sense.

2021-04-02 17:57 UTC, mulhod approved these changes

2021-04-08 14:30 UTC, RobertImbrie commented
@desilinguist Hi! Apologies for the slow response. It does look good, with one exception! On line 754, you change
```
     replace_blanks_with : value, ``dict``, or ``None``, default=None
```
to
```
     replace_blanks_with : value, ``dict``, or ``None``, default=``None``
```
In both sklearn and the previous pushes, the `default=ExampleVariable` section of the parameter header typically doesn't have quotes.

On a related note, did you have any input on using 'value' vs. `Number`? I included a question about it in my initial comment.

2021-04-08 15:07 UTC, desilinguist commented
@RobertImbrie good catch, please feel free to fix that quote issue. And yes, number instead of value seems like a better way to describe it! Please go ahead an make that change as well.

2021-04-09 17:20 UTC, RobertImbrie commented
@desilinguist Changes have been pushed!

2021-04-09 17:30 UTC, desilinguist approved these changes
LGTM! 🎉

2021-04-13 00:50 UTC, merged