Infrastructure for logging to wandb
EducationalTestingService/skll pull request #758
Opened 2023-12-06 02:12 UTC by tamarl08

This PR adds initial infrastructure for Wanda logging, including a configuration field to enable W&B, a wand interface class, documentation and tests.

2023-12-06 02:12 UTC, pep8speaks commented
Hello @tamarl08! Thanks for opening this PR. 









* In the file [`tests/test_input.py`](https://github.com/EducationalTestingService/skll/blob/59831c6a09243a6224d6afbba26930bbb51f8424/tests/test_input.py):

> [Line 1802:101](https://github.com/EducationalTestingService/skll/blob/59831c6a09243a6224d6afbba26930bbb51f8424/tests/test_input.py#L1802): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 100 characters)
> [Line 1821:101](https://github.com/EducationalTestingService/skll/blob/59831c6a09243a6224d6afbba26930bbb51f8424/tests/test_input.py#L1821): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 100 characters)
> [Line 1828:101](https://github.com/EducationalTestingService/skll/blob/59831c6a09243a6224d6afbba26930bbb51f8424/tests/test_input.py#L1828): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 100 characters)
> [Line 1833:101](https://github.com/EducationalTestingService/skll/blob/59831c6a09243a6224d6afbba26930bbb51f8424/tests/test_input.py#L1833): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 100 characters)



Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2023-12-07 19:04 UTC, desilinguist requested changes
Is there a reason the coverage checks are not being met?

2023-12-07 19:04 UTC, desilinguist commented on doc/run_experiment.rst
> +    3. Note that when using W&B logging, the skll run may take significantly longer due to the network traffic being
```suggestion
    3. Note that when using W&B logging, a SKLL run may take significantly longer due to the network traffic being
```

2023-12-07 19:04 UTC, desilinguist commented on skll/config/__init__.py
> +                "Please specify both wandb_entity and wandb_project"
```suggestion
                "Logging to W&B not enabled since either `wandb_entity` or `wandb_project` is not specified!"
```

2023-12-09 04:45 UTC, mulhod approved these changes

2023-12-10 19:24 UTC, merged